-- ==============================================================================
-- PRODUCTION SCHEMA - SaaS POS
-- Consolidated script to create the entire database from scratch.
-- ==============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. BASE TABLES (Profiles, Products, etc.)
-- ==========================================

-- PROFILES (Extends auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  business_name TEXT,
  address TEXT,
  phone TEXT,
  tax_id TEXT,
  currency TEXT DEFAULT 'USD',
  logo_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- PRODUCTS (Inventory)
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  icon TEXT,
  category TEXT,
  image TEXT,
  stock INTEGER NOT NULL DEFAULT 0,
  min_stock INTEGER DEFAULT 5,
  owner_id UUID REFERENCES auth.users(id), -- Added for SaaS isolation
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- CASH REGISTERS
CREATE TABLE IF NOT EXISTS public.cash_registers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  opening_amount NUMERIC NOT NULL,
  closing_amount NUMERIC,
  status TEXT CHECK (status IN ('open', 'closed')) DEFAULT 'open',
  opened_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  closed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- SALES
CREATE TABLE IF NOT EXISTS public.sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  cash_register_id BIGINT REFERENCES public.cash_registers(id),
  total NUMERIC NOT NULL,
  payment_method TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- SALE ITEMS
CREATE TABLE IF NOT EXISTS public.sale_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT REFERENCES public.sales(id) NOT NULL,
  product_id BIGINT REFERENCES public.products(id),
  product_name TEXT NOT NULL,
  qty INTEGER NOT NULL,
  price NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 2. PURCHASES & EXPENSES MODULE
-- ==========================================

-- EXPENSE CATEGORIES
CREATE TABLE IF NOT EXISTS public.expense_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  owner_id UUID REFERENCES auth.users(id), -- Added for SaaS isolation
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- EXPENSES
CREATE TABLE IF NOT EXISTS public.expenses (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  category_id BIGINT REFERENCES public.expense_categories(id),
  amount NUMERIC NOT NULL,
  description TEXT NOT NULL,
  date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  receipt_url TEXT,
  user_id UUID REFERENCES auth.users(id),
  owner_id UUID REFERENCES auth.users(id), -- Added for SaaS isolation
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- PURCHASES
CREATE TABLE IF NOT EXISTS public.purchases (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  supplier_name TEXT NOT NULL,
  total NUMERIC NOT NULL DEFAULT 0,
  status TEXT CHECK (status IN ('pending', 'completed', 'cancelled')) DEFAULT 'pending',
  date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID REFERENCES auth.users(id),
  owner_id UUID REFERENCES auth.users(id), -- Added for SaaS isolation
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- PURCHASE ITEMS
CREATE TABLE IF NOT EXISTS public.purchase_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id UUID REFERENCES public.purchases(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id),
  qty INTEGER NOT NULL,
  cost NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 3. FINANCIAL MODULE (Accounts & Transactions)
-- ==========================================

-- ACCOUNTS (Caja / Bancos)
CREATE TABLE IF NOT EXISTS public.accounts (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT CHECK (type IN ('cash', 'bank')) NOT NULL,
  balance NUMERIC NOT NULL DEFAULT 0,
  currency TEXT DEFAULT 'USD',
  is_default BOOLEAN DEFAULT false,
  owner_id UUID REFERENCES auth.users(id), -- Added for SaaS isolation
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TRANSACTIONS (Immutable Ledger)
CREATE TABLE IF NOT EXISTS public.transactions (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  account_id UUID REFERENCES public.accounts(id),
  type TEXT CHECK (type IN ('income', 'expense')) NOT NULL,
  amount NUMERIC NOT NULL,
  description TEXT,
  reference_type TEXT CHECK (reference_type IN ('sale', 'purchase', 'expense', 'manual')),
  reference_id TEXT, -- Changed to TEXT to support BigInt IDs from Sales
  date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  owner_id UUID REFERENCES auth.users(id), -- Added for SaaS isolation
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 4. MULTI-USER MODULE (Teams)
-- ==========================================

-- TEAM MEMBERS
CREATE TABLE IF NOT EXISTS public.team_members (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  owner_id UUID REFERENCES auth.users(id) NOT NULL, -- The company owner
  role TEXT CHECK (role IN ('admin', 'cashier')) NOT NULL DEFAULT 'cashier',
  status TEXT CHECK (status IN ('active', 'invited')) DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, owner_id)
);

-- ==========================================
-- 5. ROW LEVEL SECURITY (RLS)
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE cash_registers ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;

-- Helper Function: Get Company ID
CREATE OR REPLACE FUNCTION get_my_company_id()
RETURNS UUID AS $$
DECLARE
  v_owner_id UUID;
BEGIN
  -- Check if user is an owner (exists in profiles)
  SELECT id INTO v_owner_id FROM profiles WHERE id = auth.uid();
  
  IF v_owner_id IS NOT NULL THEN
    RETURN v_owner_id;
  END IF;

  -- Check if user is a team member
  SELECT owner_id INTO v_owner_id FROM team_members WHERE user_id = auth.uid() AND status = 'active';
  
  RETURN v_owner_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Helper Function: Get Owner ID for User (for triggers)
CREATE OR REPLACE FUNCTION get_owner_id_for_user(p_user_id UUID)
RETURNS UUID AS $$
DECLARE
  v_owner_id UUID;
BEGIN
  -- Check if user is an owner
  SELECT id INTO v_owner_id FROM profiles WHERE id = p_user_id;
  
  IF v_owner_id IS NOT NULL THEN
    RETURN v_owner_id;
  END IF;

  -- Check if user is a team member
  SELECT owner_id INTO v_owner_id FROM team_members WHERE user_id = p_user_id AND status = 'active';
  
  RETURN v_owner_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- POLICIES

-- Profiles
CREATE POLICY "Strict profile visibility" ON profiles
  FOR SELECT USING (
    id = auth.uid() -- Own profile
    OR id IN (SELECT owner_id FROM team_members WHERE user_id = auth.uid() AND status = 'active') -- My Boss
    OR id IN (SELECT user_id FROM team_members WHERE owner_id = auth.uid()) -- My Employees
  );

CREATE POLICY "Users can insert their own profile" ON profiles
  FOR INSERT WITH CHECK (id = auth.uid());

CREATE POLICY "Users can update their own profile" ON profiles
  FOR UPDATE USING (id = auth.uid());

-- Products
CREATE POLICY "View company products" ON products
  FOR SELECT USING (owner_id = get_my_company_id());

CREATE POLICY "Manage company products" ON products
  FOR ALL USING (owner_id = get_my_company_id());

-- Sales & Items
CREATE POLICY "View company sales" ON sales
  FOR SELECT USING (
    user_id = auth.uid() OR 
    user_id IN (SELECT user_id FROM team_members WHERE owner_id = auth.uid()) OR
    auth.uid() IN (SELECT owner_id FROM team_members WHERE user_id = sales.user_id)
  );
  -- Note: Ideally we should add owner_id to sales table for easier RLS, but for now we infer via user_id

CREATE POLICY "Create sales" ON sales
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "View sale items" ON sale_items
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM sales WHERE id = sale_items.sale_id)
  );

CREATE POLICY "Create sale items" ON sale_items
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM sales WHERE id = sale_items.sale_id AND user_id = auth.uid())
  );

-- Financials (Accounts & Transactions)
CREATE POLICY "View company accounts" ON accounts
  FOR SELECT USING (owner_id = get_my_company_id());

CREATE POLICY "Manage company accounts" ON accounts
  FOR ALL USING (owner_id = get_my_company_id());

CREATE POLICY "View company transactions" ON transactions
  FOR SELECT USING (owner_id = get_my_company_id());

CREATE POLICY "Manage company transactions" ON transactions
  FOR ALL USING (owner_id = get_my_company_id());

-- Purchases & Expenses
CREATE POLICY "View company purchases" ON purchases
  FOR SELECT USING (owner_id = get_my_company_id());
CREATE POLICY "Manage company purchases" ON purchases
  FOR ALL USING (owner_id = get_my_company_id());

CREATE POLICY "View company expenses" ON expenses
  FOR SELECT USING (owner_id = get_my_company_id());
CREATE POLICY "Manage company expenses" ON expenses
  FOR ALL USING (owner_id = get_my_company_id());

CREATE POLICY "View company expense categories" ON expense_categories
  FOR SELECT USING (owner_id = get_my_company_id());
CREATE POLICY "Manage company expense categories" ON expense_categories
  FOR ALL USING (owner_id = get_my_company_id());

-- Team Members
CREATE POLICY "View team members" ON team_members
  FOR SELECT USING (
    owner_id = auth.uid() OR user_id = auth.uid()
  );

CREATE POLICY "Manage team members" ON team_members
  FOR ALL USING (owner_id = auth.uid());


-- ==========================================
-- 6. TRIGGERS & AUTOMATION
-- ==========================================

-- Trigger to auto-assign owner_id on insert
CREATE OR REPLACE FUNCTION set_owner_id_trigger()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.owner_id IS NULL THEN
    NEW.owner_id := get_my_company_id();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Apply owner_id trigger
CREATE TRIGGER set_owner_id_products BEFORE INSERT ON products FOR EACH ROW EXECUTE FUNCTION set_owner_id_trigger();
CREATE TRIGGER set_owner_id_accounts BEFORE INSERT ON accounts FOR EACH ROW EXECUTE FUNCTION set_owner_id_trigger();
CREATE TRIGGER set_owner_id_purchases BEFORE INSERT ON purchases FOR EACH ROW EXECUTE FUNCTION set_owner_id_trigger();
CREATE TRIGGER set_owner_id_expenses BEFORE INSERT ON expenses FOR EACH ROW EXECUTE FUNCTION set_owner_id_trigger();
CREATE TRIGGER set_owner_id_expense_categories BEFORE INSERT ON expense_categories FOR EACH ROW EXECUTE FUNCTION set_owner_id_trigger();


-- Handle New Sale (Financial Transaction)
CREATE OR REPLACE FUNCTION handle_new_sale()
RETURNS TRIGGER AS $$
DECLARE
  v_account_id UUID;
  v_account_type TEXT;
  v_owner_id UUID;
BEGIN
  -- Get Owner ID
  v_owner_id := get_owner_id_for_user(new.user_id);
  IF v_owner_id IS NULL THEN
    RAISE EXCEPTION 'User % has no company owner', new.user_id;
  END IF;

  -- Determine account type
  IF new.payment_method = 'Efectivo' THEN
    v_account_type := 'cash';
  ELSE
    v_account_type := 'bank';
  END IF;

  -- Find Account for THIS company
  SELECT id INTO v_account_id 
  FROM accounts 
  WHERE type = v_account_type 
    AND owner_id = v_owner_id 
  LIMIT 1;

  -- Create Account if missing
  IF v_account_id IS NULL THEN
    INSERT INTO accounts (name, type, is_default, owner_id) 
    VALUES (
      CASE WHEN v_account_type = 'cash' THEN 'Caja General' ELSE 'Banco Principal' END, 
      v_account_type, 
      true,
      v_owner_id
    )
    RETURNING id INTO v_account_id;
  END IF;

  -- Create Transaction
  INSERT INTO transactions (account_id, type, amount, description, reference_type, reference_id, date, owner_id)
  VALUES (v_account_id, 'income', new.total, 'Venta #' || new.id, 'sale', new.id::text, new.created_at, v_owner_id);

  -- Update Balance
  UPDATE accounts SET balance = balance + new.total WHERE id = v_account_id;

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_new_sale
  AFTER INSERT ON sales
  FOR EACH ROW EXECUTE FUNCTION handle_new_sale();


-- Handle New Expense (Financial Transaction)
CREATE OR REPLACE FUNCTION handle_new_expense()
RETURNS TRIGGER AS $$
DECLARE
  v_account_id UUID;
  v_owner_id UUID;
BEGIN
  v_owner_id := get_my_company_id(); 

  -- Assume Cash
  SELECT id INTO v_account_id FROM accounts WHERE type = 'cash' AND owner_id = v_owner_id LIMIT 1;
  
  IF v_account_id IS NULL THEN
    INSERT INTO accounts (name, type, is_default, owner_id) 
    VALUES ('Caja General', 'cash', true, v_owner_id) 
    RETURNING id INTO v_account_id;
  END IF;

  -- Create Transaction
  INSERT INTO transactions (account_id, type, amount, description, reference_type, reference_id, date, owner_id)
  VALUES (v_account_id, 'expense', new.amount, new.description, 'expense', new.id::text, new.date, v_owner_id);

  -- Update Balance
  UPDATE accounts SET balance = balance - new.amount WHERE id = v_account_id;

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_new_expense
  AFTER INSERT ON expenses
  FOR EACH ROW EXECUTE FUNCTION handle_new_expense();


-- Handle New Purchase (Financial Transaction)
CREATE OR REPLACE FUNCTION handle_new_purchase()
RETURNS TRIGGER AS $$
DECLARE
  v_account_id UUID;
  v_owner_id UUID;
BEGIN
  v_owner_id := get_my_company_id();

  -- Assume Cash
  SELECT id INTO v_account_id FROM accounts WHERE type = 'cash' AND owner_id = v_owner_id LIMIT 1;
  
  IF v_account_id IS NULL THEN
    INSERT INTO accounts (name, type, is_default, owner_id) 
    VALUES ('Caja General', 'cash', true, v_owner_id) 
    RETURNING id INTO v_account_id;
  END IF;

  -- Create Transaction
  INSERT INTO transactions (account_id, type, amount, description, reference_type, reference_id, date, owner_id)
  VALUES (v_account_id, 'expense', new.total, 'Compra a ' || new.supplier_name, 'purchase', new.id::text, new.date, v_owner_id);

  -- Update Balance
  UPDATE accounts SET balance = balance - new.total WHERE id = v_account_id;

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_new_purchase
  AFTER INSERT ON purchases
  FOR EACH ROW EXECUTE FUNCTION handle_new_purchase();


-- Handle User Creation (Profile)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, business_name)
  VALUES (new.id, new.raw_user_meta_data->>'business_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
